name: fooderlich
description: A Flutter food project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.9
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.1.0
  google_fonts: ^8.0.0
  intl: ^0.20.0
  provider: ^6.1.5+1
  shared_preferences: ^2.5.0
  smooth_page_indicator: ^2.0.0
  url_launcher: ^6.3.0
  uuid: ^4.0.0
  webview_flutter: ^4.0.0

dev_dependencies:
  fake_async: ^1.3.1
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.3.0
  webview_flutter_platform_interface: ^2.15.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/food_pics/
    - assets/magazine_pics/
    - assets/sample_data/
    - assets/profile_pics/
